title: Michael Mayntz Petersen Portefølje


author: Michael Mayntz Petersen


navbar-links:
  Blog: "index"
  Om Mig: "about"
  Læringsmål: 
    - Generalle Læringsmål: "generalLearningObjectives"
    - Microservice: "microservice"
    - IT Sikkerhed: "itSecurity"
  Læringsplan: "learningPlan"
  Litteraturliste : "resources"
  
social-network-links:
  email: "naxzor1989@hotmail.com"
  github: "naxzor"
  linkedin: michael-mayntz-petersen

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: "/Portfolie" # the subpath of your site, e.g. /blog
#url: "http://localhost:4000/" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-remote-theme
