title: Michael Mayntz Petersen Portefolje


author: Michael Mayntz Petersen


navbar-links:
  Blog: "index"
  Om Mig: "about"
  Læringsmål: 
    - Generalle Læringsmål: "generalLearningObjectives"
    - Microservice: "microservice"
    - IT Sikkerhed: "itSecurity"
  Læringsplan: "learningPlan"
  Litteraturliste : "resources"
  
social-network-links:
  email: "naxzor1989@hotmail.com"
  github: "naxzor"
  linkedin: michael-mayntz-petersen

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb

# Build settings
remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
